pipeline { 
    agent any
	options { timestamps () }	
    stages {
        stage('Build') { 
            steps {
                echo $JOB_NAME
				echo "current build number: ${currentBuild.number}"
				echo "workspace: ${workspace}"
                }
            }
        }
        post {
            success {
                echo "Pipeline successful"
        }
			failure {
				echo "The Pipeline failed :("
                }

            }
}